# Generated by Django 2.1.3 on 2019-01-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('record_number', models.PositiveIntegerField(null=True)),
                ('device_man', models.CharField(choices=[('Abbot', 'Abbot'), ('Biotronik', 'Biotronik'), ('Boston Scientific', 'Boston Scientific'), ('Medtronic', 'Medtronic'), ('Sorin', 'Sorin')], max_length=30, null=True)),
                ('device_name', models.CharField(max_length=30, null=True)),
                ('implant_date', models.DateField(null=True)),
                ('device_serial', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('oos_type', models.CharField(choices=[('In Clinic Periodic', 'In Clinic Periodic'), ('In Clinic Call Back', 'In Clinic Call Back'), ('Remote Periodic', 'Remote Periodic'), ('Remote Early Detection', 'Remote Early Detection')], default='In Clinic Periodic', max_length=25)),
                ('batt_volt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('oos_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'ordering': ('-oos_date',),
            },
        ),
    ]
