# Generated by Django 2.1.4 on 2019-01-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oos',
            options={'ordering': ('-oos_date',)},
        ),
        migrations.AlterField(
            model_name='oos',
            name='oos_date',
            field=models.DateTimeField(),
        ),
    ]
