# Generated by Django 2.1.3 on 2018-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oos',
            old_name='type',
            new_name='oos_type',
        ),
        migrations.AddField(
            model_name='client',
            name='record_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
