# Generated by Django 2.1.4 on 2019-01-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190103_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oos',
            name='oos_type',
            field=models.CharField(choices=[('in_clinic_periodic', ' In Clinic Periodic'), ('in_clinic_callback', 'In Clinic Call Back'), ('remote_periodic', 'Remote Periodic'), ('remote_early_detection', 'Remote Early Detection')], default='in_clinic_periodic', max_length=25),
        ),
    ]
