# Generated by Django 2.1.3 on 2019-01-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190104_0550'),
        ('clients', '0003_auto_20190104_1112'),
    ]

    operations = [
    ]
