# Generated by Django 2.1.3 on 2019-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_merge_20190105_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oos',
            options={'ordering': ('-oos_date',)},
        ),
        migrations.AddField(
            model_name='client',
            name='device_man',
            field=models.CharField(choices=[('Abbot', 'Abbot'), ('Biotronik', 'Biotronik'), ('Boston Scientific', 'Boston Scientific'), ('Medtronic', 'Medtronic'), ('Sorin', 'Sorin')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='device_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='implant_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oos',
            name='oos_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oos',
            name='oos_type',
            field=models.CharField(choices=[('In Clinic Periodic', 'In Clinic Periodic'), ('In Clinic Call Back', 'In Clinic Call Back'), ('Remote Periodic', 'Remote Periodic'), ('Remote Early Detection', 'Remote Early Detection')], default='In Clinic Periodic', max_length=25),
        ),
    ]
