# Generated by Django 2.1.3 on 2019-01-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20190109_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='device_serial',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
