# Generated by Django 2.1.3 on 2019-01-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_device_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consent_file',
            field=models.BinaryField(null=True),
        ),
    ]
