# Generated by Django 2.1.3 on 2019-01-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_consent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='consent_file',
            field=models.FileField(null=True, upload_to='consents/pdfs/'),
        ),
    ]
