# Generated by Django 2.1.3 on 2019-01-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20190123_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='consent_file',
            field=models.FileField(blank=True, null=True, upload_to='consents/pdfs/'),
        ),
    ]
