# Generated by Django 2.1.3 on 2019-01-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20190123_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='consent_file',
        ),
    ]
